### ISSUE TITLE
Is PHP 7.2 requirement really necessary?

### ISSUE THREAD

**Issue by lakiboy** [lcobucci/clock#11]
Hello!

With recent php version bump to 7.2 you broke _lcobucci/jwt_'s master branch (for PHP 7.1). I guess you'll bump up PHP version for _jwt_ package too.

However, I don't see any PHP 7.2 specific feature in _lcobucci/clock_. Maybe you can release v2.0 with PHP 7.2+ requirement, but leave v1.* with PHP 7.1.

What do you think?

P.S. https://github.com/lakiboy/damax-api-auth-bundle is no longer working with PHP 7.1. :(

**Comment by lcobucci** [comment]
Hello @lakiboy, thanks for sending this issue.

You're absolutely correct about not using any particular PHP 7.2 feature, however removing support of PHP 7.1 is strategic to reduce the amount of versions to maintain. My **personal** policy is to as much as possible support only the latest stable versions.

Some people argue that this can be seen as a BC-break, but according to [semver](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api) it's not.

With that said I disagree about bumping the major release without having changed the public API of this library.

> With recent php version bump to 7.2 you broke lcobucci/jwt's master branch (for PHP 7.1). I guess you'll bump up PHP version for jwt package too.

I'm not sure about that, the latest cronjob in Travis seems to be fine for PHP 7.1: https://travis-ci.org/lcobucci/jwt/builds/419797415

> P.S. https://github.com/lakiboy/damax-api-auth-bundle is no longer working with PHP 7.1. :(

What seems to be happening in your case is a different thing... you see, composer is quite smart about solving your dependencies according to the platform your running it.

It seems to me that you have updated your `composer.lock` in a system with PHP 7.2, this would make composer lock your dependencies in that particular platform. But then when you run `composer install` in a PHP 7.1 platform things break due to the requirements of your dependency.

I **strongly** recommend you to not use `1.1.*` as version constraint (use `^1.1` instead) and let composer resolve things properly and use `composer update` in the CI for the two different versions you use (or at least for PHP 7.1 since it looks like you're developing using PHP 7.2 now).

We had people mentioning the same thing in the doctrine packages and we wrote [this post](https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html), maybe it can help you too :smile: 

Let me know if this was helpful :+1:

**Comment by lakiboy** [comment]
Hi again!

Yes, you're completely right regarding composer.lock and PHP version I'm using. I didn't pay attention my docker container is on version 7.2. Yes, If I want to support PHP 7.1 I need to downgrade and commit relevant composer.lock i.e. 7.1 compatible. 

Regarding _1.1.*_ vs _^1.1_. I'm aware of this. Again it was my bet I was in hurry and blamed you for this.

It doesn't mean, however, I agree with your decision regarding bumping up to 7.2. But I don't have much choice, do I? :)

Thanks for your thorough and quick help.

P.S. Waiting for a stable version v4 of _lcobucci/jwt_.
