### ISSUE TITLE
Remove dependency on system time zone

### ISSUE THREAD

**Issue by slepic** [lcobucci/clock#34]
I'll just continue the discussion about UTC from #31 here....

I was just thinking why `SystemClock::forUTC()` over `SystemClock::UTC()` and my thought is that you will never need two instances of SystemClock with UTC timezone and so this instance can be self hosted in a static private property, in which case having just `UTC()` seems more reasonable to me.

```
private static ?SystemClock $utcClock = null;
public static function UTC(): SystemClock
{
  if (self::$utcClock === null) {
    self::$utcClock = new SystemClock(new \DateTimeZone('UTC'));
  }
  return self::$utcClock;
}

FrozenClock::fromUTC(): FrozenClock
{
  return new self(SystemClock::UTC()->now());
}
```

As for the BC break with nonnullable timezone in SystemClock constructor, it can be made deprecated in when SystemClock::(for)UTC() is added, and to be removed in 2.0

**Comment by lcobucci** [comment]
I'd really love if we could avoid having the responsibility of managing instances in the lib. To me that's up to the users of the lib, and in my use cases I'd end up having one more reference to the instance (which is unnecessary).

I've suggested using `SystemClock::forUTC()` because (to me) it reads like: create an instance for the UTC timezone.

**Comment by lcobucci** [comment]
I chose not to remove the dependency on system timezone but to make it explicit (allowing for us to drop the fallback behaviour). I'll consider as closed. Thanks @slepic
